openapi: 3.1.0
info:
  contact:
    email: chuck.marco@prattwhitney.com
    name: Project manager- Chuck Marco
  description: |
    Documentation of DOME RESTful APIs for use by the MRO (Maintenance, Repair and Operations) Collaboration and WST (Workscope Tool) systems.
    This documention is generated from the DOME OpenAPI Specification so is the most accurate and definitive possible.
    Every effort was made to make the DOME APIs adherent to current industry standards and recommendations such as those by the
    <a href="https://www.ietf.org/about/introduction/#about" target="_blank" rel="noopener noreferrer">Internet Engineering Task Force (IETF) for standards development for the Internet</a>.

    **Relevant specifications and RESTful API standards used by DOME**

    * <a href="https://beanvalidation.org/2.0/spec" target="_blank" rel="noopener noreferrer">API Request Validation Specification- Enforces Client API Contract</a>
    * <a href="https://www.rfc-editor.org/rfc/rfc7807" target="_blank" rel="noopener noreferrer">Problem Details for HTTP APIs- Client Error Responses</a>
    * <a href="https://datatracker.ietf.org/doc/rfc9457/" target="_blank" rel="noopener noreferrer">Problem Details for HTTP APIs (Latest)- Client Error Responses</a>
    * <a href="https://www.openapis.org/what-is-openapi" target="_blank" rel="noopener noreferrer">OpenAPI Specification (OAS)- API Development Lifecycle</a>

    ---
  title: Digital Overhaul Management of Engines (DOME)
  version: "Version: 2025-04-11"
externalDocs:
  description: Project SharePoint
servers:
- description: DBDS Devlelopment
  url: http://192.168.3.171:81/dome
- description: DBDS Stage
  url: http://192.168.3.171:82/dome
- description: P&W Stage
  url: https://dome-ui-test.prattwhitney.com/dome
security:
- bearerAuth: []
tags:
- description: "MRO (maintenance, repair and operations) Collaboration API."
  name: MRO Collab
paths:
  /v1/mro-collab/customer-approval:
    put:
      description: Updates the matching DOME record with the MRO customer approval
        date.
      operationId: updateMroCustomerApprovalDate
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MroCustomerApprovalRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              examples:
                OK:
                  description: OK
                  value: Success
              schema:
                type: string
          description: Successfully updated the matching DOME record with the MRO
            customer approval date.
        "202":
          content:
            application/json:
              examples:
                ACCEPTED:
                  description: ACCEPTED
                  value: Customer approval date is already set with the same date.
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: The request was accepted but no update was made since the date
            matches the existing customer approval date.
        "409":
          content:
            application/json:
              examples:
                CONFLICT:
                  description: CONFLICT
                  value: Customer approval date is already set with a different date.
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: The request was rejected because the date is different from
            the existing date.
      tags:
      - MRO Collab
  /v1/mro-collab/workorder:
    delete:
      description: Deletes the MRO work order from the matching DOME record.
      operationId: deleteMroWorkOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MroWorkOrderDeleteRequest"
        required: true
      responses:
        "204":
          content:
            application/json:
              schema:
                type: object
          description: The MRO work order from the matching DOME record was nulled.
        "400":
          content:
            application/json:
              examples:
                All request values fail validation.:
                  description: All request values fail validation.
                  summary: All request values made to fail validation.
                  value:
                    status: BAD_REQUEST
                    statusCode: 400
                    reason: Bad Request
                    message: "Validation failed for argument [0] in public org.springframework.http.ResponseEntity<?>\
                      \ com.pw.dome.mro.collab.workorder.MroWorkOrderController.deleteWorkOrderFromMRO(com.pw.dome.mro.collab.workorder.MroWorkOrderDeleteRequest)\
                      \ with 3 errors: [Field error in object 'mroWorkOrderDeleteRequest'\
                      \ on field 'mroShopCode': rejected value [ESAdskndsduhsudhisuhdshdshdhsdsdhishdis];\
                      \ codes [Size.mroWorkOrderDeleteRequest.mroShopCode,Size.mroShopCode,Size.java.lang.String,Size];\
                      \ arguments [org.springframework.context.support.DefaultMessageSourceResolvable:\
                      \ codes [mroWorkOrderDeleteRequest.mroShopCode,mroShopCode];\
                      \ arguments []; default message [mroShopCode],10,1]; default\
                      \ message [size must be between 1 and 10]] [Field error in object\
                      \ 'mroWorkOrderDeleteRequest' on field 'eventId': rejected value\
                      \ [-1]; codes [Min.mroWorkOrderDeleteRequest.eventId,Min.eventId,Min.java.lang.Integer,Min];\
                      \ arguments [org.springframework.context.support.DefaultMessageSourceResolvable:\
                      \ codes [mroWorkOrderDeleteRequest.eventId,eventId]; arguments\
                      \ []; default message [eventId],1]; default message [must be\
                      \ greater than or equal to 1]] [Field error in object 'mroWorkOrderDeleteRequest'\
                      \ on field 'esn': rejected value [723821odaauasashashashahsuhaushuahsasas];\
                      \ codes [Size.mroWorkOrderDeleteRequest.esn,Size.esn,Size.java.lang.String,Size];\
                      \ arguments [org.springframework.context.support.DefaultMessageSourceResolvable:\
                      \ codes [mroWorkOrderDeleteRequest.esn,esn]; arguments []; default\
                      \ message [esn],20,1]; default message [size must be between\
                      \ 1 and 20]]"
                    errors:
                    - "mroShopCode: size must be between 1 and 10"
                    - "eventId: must be greater than or equal to 1"
                    - "esn: size must be between 1 and 20"
                One request value fails validation.:
                  description: One request value fails validation.
                  summary: One request value is null and fails validation.
                  value:
                    status: BAD_REQUEST
                    statusCode: 400
                    reason: Bad Request
                    message: "Validation failed for argument [0] in public org.springframework.http.ResponseEntity<?>\
                      \ com.pw.dome.mro.collab.workorder.MroWorkOrderController.deleteWorkOrderFromMRO(com.pw.dome.mro.collab.workorder.MroWorkOrderDeleteRequest):\
                      \ [Field error in object 'mroWorkOrderDeleteRequest' on field\
                      \ 'eventId': rejected value [null]; codes [NotNull.mroWorkOrderDeleteRequest.eventId,NotNull.eventId,NotNull.java.lang.Integer,NotNull];\
                      \ arguments [org.springframework.context.support.DefaultMessageSourceResolvable:\
                      \ codes [mroWorkOrderDeleteRequest.eventId,eventId]; arguments\
                      \ []; default message [eventId]]; default message [must not\
                      \ be null]]"
                    errors:
                    - "eventId: must not be null"
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Bad Request
        "404":
          content:
            application/json:
              examples:
                EventId doesn't match.:
                  description: EventId doesn't match.
                  summary: Error response when request EventId not matched.
                  value:
                    status: NOT_FOUND
                    statusCode: 404
                    reason: Not Found
                    message: 'No matching records to update found. ESN=''723821''
                      has 1 match(es). EventId=''40436799'' has 0 match(es). ShopCode=''ESA''
                      has 3737 match(es). '
                    errors:
                    - 'No matching records to update found. ESN=''723821'' has 1 match(es).
                      EventId=''40436799'' has 0 match(es). ShopCode=''ESA'' has 3737
                      match(es). '
                ShopCode doesn't match.:
                  description: ShopCode doesn't match.
                  summary: Error response when request ShopCode not matched.
                  value:
                    status: NOT_FOUND
                    statusCode: 404
                    reason: Not Found
                    message: 'No matching records to update found. ESN=''723821''
                      has 1 match(es). EventId=''4043679'' has 1 match(es). ShopCode=''ESAAA''
                      has 0 match(es). '
                    errors:
                    - 'No matching records to update found. ESN=''723821'' has 1 match(es).
                      EventId=''4043679'' has 1 match(es). ShopCode=''ESAAA'' has
                      0 match(es). '
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Not Found
      tags:
      - MRO Collab
    post:
      description: Updates the matching DOME record with the MRO work order.
      operationId: updateMroShopCodeAndWorkOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MroWorkOrderUpdateRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: WorkOrder updated for matching DOME record.
        "400":
          content:
            application/json:
              examples:
                All request values fail validation.:
                  description: All request values fail validation.
                  summary: All request values made to fail validation.
                  value:
                    status: BAD_REQUEST
                    statusCode: 400
                    reason: Bad Request
                    message: "Validation failed for argument [0] in public org.springframework.http.ResponseEntity<java.lang.String>\
                      \ com.pw.dome.mro.collab.workorder.MroWorkOrderController.getMroInfo(com.pw.dome.mro.collab.workorder.MroWorkOrderRequest)\
                      \ with 4 errors: [Field error in object 'mroWorkOrderRequest'\
                      \ on field 'mroShopCode': rejected value [ESAjidjowjdosjdoijsdojsodjsdoisd];\
                      \ codes [Length.mroWorkOrderRequest.mroShopCode,Length.mroShopCode,Length.java.lang.String,Length];\
                      \ arguments [org.springframework.context.support.DefaultMessageSourceResolvable:\
                      \ codes [mroWorkOrderRequest.mroShopCode,mroShopCode]; arguments\
                      \ []; default message [mroShopCode],10,1]; default message [length\
                      \ must be between 1 and 10]] [Field error in object 'mroWorkOrderRequest'\
                      \ on field 'esn': rejected value [72382112902912912091290120912098u12];\
                      \ codes [Length.mroWorkOrderRequest.esn,Length.esn,Length.java.lang.String,Length];\
                      \ arguments [org.springframework.context.support.DefaultMessageSourceResolvable:\
                      \ codes [mroWorkOrderRequest.esn,esn]; arguments []; default\
                      \ message [esn],20,1]; default message [length must be between\
                      \ 1 and 20]] [Field error in object 'mroWorkOrderRequest' on\
                      \ field 'eventId': rejected value [-1]; codes [Range.mroWorkOrderRequest.eventId,Range.eventId,Range.java.lang.Integer,Range];\
                      \ arguments [org.springframework.context.support.DefaultMessageSourceResolvable:\
                      \ codes [mroWorkOrderRequest.eventId,eventId]; arguments [];\
                      \ default message [eventId],9223372036854775807,1]; default\
                      \ message [must be between 1 and 9223372036854775807]] [Field\
                      \ error in object 'mroWorkOrderRequest' on field 'mroWorkOrder':\
                      \ rejected value [0123456789mjdoiasjodjnwoidjowdjoidjoihjndo];\
                      \ codes [Length.mroWorkOrderRequest.mroWorkOrder,Length.mroWorkOrder,Length.java.lang.String,Length];\
                      \ arguments [org.springframework.context.support.DefaultMessageSourceResolvable:\
                      \ codes [mroWorkOrderRequest.mroWorkOrder,mroWorkOrder]; arguments\
                      \ []; default message [mroWorkOrder],25,1]; default message\
                      \ [length must be between 1 and 25]]"
                    errors:
                    - "mroShopCode: length must be between 1 and 10"
                    - "esn: length must be between 1 and 20"
                    - "eventId: must be between 1 and 9223372036854775807"
                    - "mroWorkOrder: length must be between 1 and 25"
                One request value fails validation.:
                  description: One request value fails validation.
                  summary: One request value is null and fails validation.
                  value:
                    status: BAD_REQUEST
                    statusCode: 400
                    reason: Bad Request
                    message: "Validation failed for argument [0] in public org.springframework.http.ResponseEntity<java.lang.String>\
                      \ com.pw.dome.mro.collab.workorder.MroWorkOrderController.getMroInfo(com.pw.dome.mro.collab.workorder.MroWorkOrderRequest):\
                      \ [Field error in object 'mroWorkOrderRequest' on field 'eventId':\
                      \ rejected value [null]; codes [NotNull.mroWorkOrderRequest.eventId,NotNull.eventId,NotNull.java.lang.Integer,NotNull];\
                      \ arguments [org.springframework.context.support.DefaultMessageSourceResolvable:\
                      \ codes [mroWorkOrderRequest.eventId,eventId]; arguments [];\
                      \ default message [eventId]]; default message [The field may\
                      \ not be null.]]"
                    errors:
                    - "eventId: The field may not be null."
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Bad Request
        "404":
          content:
            application/json:
              examples:
                ESN doesn't match.:
                  description: ESN doesn't match.
                  summary: Error response when request ESN not matched.
                  value:
                    status: NOT_FOUND
                    statusCode: 404
                    reason: Not Found
                    message: 'No matching records to update found. ESN=''72382111''
                      has 0 match(es). EventId=''4043679'' has 1 match(es). ShopCode=''ESA''
                      has 3737 match(es). '
                    errors:
                    - 'No matching records to update found. ESN=''72382111'' has 0
                      match(es). EventId=''4043679'' has 1 match(es). ShopCode=''ESA''
                      has 3737 match(es). '
                ShopCode doesn't match.:
                  description: ShopCode doesn't match.
                  summary: Error response when request ShopCode not matched.
                  value:
                    status: NOT_FOUND
                    statusCode: 404
                    reason: Not Found
                    message: 'No matching records to update found. ESN=''723821''
                      has 1 match(es). EventId=''4043679'' has 1 match(es). ShopCode=''ESAAA''
                      has 0 match(es). '
                    errors:
                    - 'No matching records to update found. ESN=''723821'' has 1 match(es).
                      EventId=''4043679'' has 1 match(es). ShopCode=''ESAAA'' has
                      0 match(es). '
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Not Found
      tags:
      - MRO Collab
  /v1/workscopetool/pushworkscopedate:
    post:
      description: Updates the matching DOME record with the MRO customer approval
        date.
      operationId: updateWorkscopeInitiationDate
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WstRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              examples:
                OK:
                  description: OK
                  value: Update workscope date successful.
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Successfully updated the matching DOME record with the MRO
            customer approval date.
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: The request failed API contract compliance.
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: "No DOME records matched the provided esn, smiNumber, maintenanceId\
            \ and serviceTrackerId."
      tags:
      - Workscope Tool
components:
  schemas:
    ErrorResponse:
      type: object
      description: Application response schema.
      properties:
        errors:
          type: array
          description: Chain of application error messages.
          items:
            type: string
        message:
          type: string
          description: Application message.
        reason:
          type: string
          description: "The HttpStatus Reason Phrase  (e.g., NOT FOUND)."
        status:
          type: string
          description: "The HttpStatus name (e.g., NOT_FOUND)."
        statusCode:
          type: integer
          format: int32
          description: "The HttpStatus value  (e.g., 404)."
    MroCustomerApprovalRequest:
      type: object
      description: Encapsulates and ensures RESTful API contract compliance of the
        updateMroCustomerApprovalDate request.
      properties:
        customerApprovalDateTime:
          type: string
          format: date-time
          description: Strict ISO 8601 Format (yyyy-MM-dd'T'HH:mm:ss) - "2023-12-12T23:12:12"
            or Relaxed ISO 8601 Format (yyyy-MM-dd HH:mm:ss) - "2023-12-12 23:12:12"
        esn:
          type: string
          description: Engine Serial Number
          maxLength: 20
          minLength: 1
        eventId:
          type: integer
          format: int32
          description: supplanted by maintenanceId and serviceTrackerId
        maintenanceId:
          type: integer
          format: int32
          description: many-to-one with serviceTrackerId
        mroShopCode:
          type: string
          description: shop code used by MRO system
          maxLength: 10
          minLength: 1
        mroWorkOrder:
          type: string
          description: work order (AKA SMI) used by MRO system
          maxLength: 25
          minLength: 1
        serviceTrackerId:
          type: integer
          format: int32
          description: one-to-many with maintenanceId
      required:
      - customerApprovalDateTime
      - esn
      - maintenanceId
      - mroShopCode
      - mroWorkOrder
      - serviceTrackerId
    MroWorkOrderDeleteRequest:
      type: object
      description: Encapsulates and ensures RESTful API contract compliance of the
        deleteMroWorkOrder request.
      properties:
        esn:
          type: string
          description: Engine Serial Number
          maxLength: 20
          minLength: 1
        eventId:
          type: integer
          format: int32
          description: supplanted by maintenanceId and serviceTrackerId
        maintenanceId:
          type: integer
          format: int32
          description: many-to-one with serviceTrackerId
        mroShopCode:
          type: string
          description: shop code used by MRO system
          maxLength: 10
          minLength: 1
        serviceTrackerId:
          type: integer
          format: int32
          description: one-to-many with maintenanceId
      required:
      - esn
      - maintenanceId
      - mroShopCode
      - serviceTrackerId
    MroWorkOrderUpdateRequest:
      type: object
      description: Encapsulates and ensures RESTful API contract compliance of the
        updateWstShopCodeAndWorkOrder request.
      properties:
        esn:
          type: string
          description: Engine Serial Number
          maxLength: 20
          minLength: 1
        eventId:
          type: integer
          format: int32
          description: supplanted by maintenanceId and serviceTrackerId
        maintenanceId:
          type: integer
          format: int32
          description: many-to-one with serviceTrackerId
        mroShopCode:
          type: string
          description: shop code used by MRO system
          maxLength: 10
          minLength: 1
        mroWorkOrder:
          type: string
          description: work order (AKA SMI) used by MRO system
          maxLength: 25
          minLength: 1
        publishedDateTime:
          type: string
          format: date-time
          description: Strict ISO 8601 Format (yyyy-MM-dd'T'HH:mm:ss) - "2023-12-12T23:12:12"
            or Relaxed ISO 8601 Format (yyyy-MM-dd HH:mm:ss) - "2023-12-12 23:12:12"
        serviceTrackerId:
          type: integer
          format: int32
          description: one-to-many with maintenanceId
      required:
      - esn
      - maintenanceId
      - mroShopCode
      - mroWorkOrder
      - publishedDateTime
      - serviceTrackerId
    WstRequest:
      type: object
      description: Encapsulates and ensures RESTful API contract compliance of the
        updateWorkscopeInitiationDate request.
      properties:
        esn:
          type: string
          description: Engine Serial Number
          minLength: 1
        eventId:
          type: integer
          format: int32
          description: supplanted by maintenanceId and serviceTrackerId
        maintenanceId:
          type: integer
          format: int32
          description: many-to-one with serviceTrackerId
        operator:
          type: string
          description: operator name
          minLength: 1
        provider:
          type: string
          minLength: 1
        serviceTrackerId:
          type: integer
          format: int32
          description: one-to-many with maintenanceId
        smiNumber:
          type: string
          description: SMI is also know as work order
          minLength: 1
        svClassification:
          type: string
          minLength: 1
        wscreatedBy:
          type: string
        wsinitiationDateTime:
          type: string
          format: date-time
        wspublishedDateTime:
          type: string
          format: date-time
      required:
      - esn
      - maintenanceId
      - operator
      - provider
      - serviceTrackerId
      - smiNumber
      - svClassification
  securitySchemes:
    bearerAuth:
      bearerFormat: jwt
      description: JWT Bearer Authorization.
      scheme: bearer
      type: http
